### ISSUE TITLE
`begin dev` fails when using Node 16 via node version managers (nvm, fnm…)

### ISSUE THREAD

**Issue by colepeters** [beginner-corp/cli#121]
# Reproduction

1. Install [nvm](https://github.com/nvm-sh/nvm)
1. Install Node 16 via nvm: `nvm install 16 && nvm use 16`
1. Create a new begin project: `begin new foo`
1. Run the project: `cd foo`, `begin dev`

The following error is emitted:
```
Error
Process exited with 1

node:internal/modules/cjs/loader:985
  const err = new Error(message);
              ^

Error: Cannot find module 'aws-sdk/clients/sns'
Require stack:
- /Users/<USER>/Developer/<FOO>/node_modules/@architect/functions/src/events/publish.js
- /Users/<USER>/Developer/<FOO>/node_modules/@architect/functions/src/events/index.js
- /Users/<USER>/Developer/<FOO>/node_modules/@architect/functions/src/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at eventFactory (/Users/<USER>/Developer/<FOO>/node_modules/@architect/functions/src/events/publish.js:89:15)
    at publishFactory (/Users/<USER>/Developer/<FOO>/node_modules/@architect/functions/src/events/publish.js:14:20)
    at eventsAndQueuesFactory (/Users/<USER>/Developer/<FOO>/node_modules/@architect/functions/src/events/index.js:5:17)
    at Object. (/Users/<USER>/Developer/<FOO>/node_modules/@architect/functions/src/index.js:43:33)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/<USER>/Developer/<FOO>/node_modules/@architect/functions/src/events/publish.js',
    '/Users/<USER>/Developer/<FOO>/node_modules/@architect/functions/src/events/index.js',
    '/Users/<USER>/Developer/<FOO>/node_modules/@architect/functions/src/index.js'
  ]
}
```

# Environment
- Begin CLI: `Begin main-fb4bbd1`
- OS: macOS 12
- Shell: ZSH

Also reported by @tbeseda to happen when using [fnm](https://github.com/Schniz/fnm) so I presume this may be an issue with any node version manager.

# Workaround
Error can be eliminated by installing `@architect/architect` or `aws-sdk` as a dev dependency in the project.

**Comment by ryanblock** [comment]
Patched in `@architect/functions` 5.3.1, which should be pulled into new projects automatically. Thank you!
