### ISSUE TITLE
begin dev should report when another begin dev is running

### ISSUE THREAD

**Issue by macdonst** [beginner-corp/cli#45]
If you have a terminal open with `begin dev` running and you try and run it from another terminal then the error is:

```
Begin dev server (0.0.29)

✓ Sandbox Found Architect project manifest: .arc
✓ Sandbox No custom testing environment variables found
```

Then it exits.

**Comment by macdonst** [comment]
Not reproducible in 0.18.1. It now shows this error:

```
Error: Port 3333 (http) is already in use, please select another with prefs.arc
/snapshot/cli/node_modules/run-series/index.js:11
      if (cb) cb(err, results)
              ^

Error: Sandbox is not running
    at Object.end (/snapshot/cli/node_modules/@architect/sandbox/src/index.js)
    at watching (/snapshot/cli/node_modules/@architect/sandbox/src/cli/index.js)
    at /snapshot/cli/node_modules/@architect/sandbox/src/index.js
    at /snapshot/cli/node_modules/@architect/sandbox/src/sandbox/index.js
    at end (/snapshot/cli/node_modules/run-series/index.js:11:15)
    at done (/snapshot/cli/node_modules/run-series/index.js:14:10)
    at each (/snapshot/cli/node_modules/run-series/index.js:19:43)
    at done (/snapshot/cli/node_modules/@architect/sandbox/src/sandbox/ports.js)
    at end (/snapshot/cli/node_modules/run-series/index.js:11:15)
    at done (/snapshot/cli/node_modules/run-series/index.js:14:10)
 ```
